bonus:
  # Permissão para aumentar o limite de stack por item
  stack:
    # Sem permissão
    default: 5
    # moneyfarm.stack1
    stack1: 15
    # moneyfarm.stack2
    stack2: 20
    # moneyfarm.stack3
    stack3: 25
    # moneyfarm.stack4
    stack4: 30
    # Sem limite de stack
    # moneyfarm.stackinfinite
    stackinfinite: -1
  # Permissão para multiplicar a quantidade de coins gerada
  generate:
    # moneyfarm.generate1
    generate1: 1.15
    # moneyfarm.generate2
    generate2: 1.25
    # moneyfarm.generate3
    generate3: 1.35
    # moneyfarm.generate4
    generate4: 1.45
    # moneyfarm.generate5
    generate5: 1.55

currency-format:
  - ''
  - 'k'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'OC'
  - 'N'
  - 'D'
  - 'UN'
  - 'DD'
  - 'TR'
  - 'QT'
  - 'QN'
  - 'SD'
  - 'SPD'
  - 'OD'
  - 'ND'
  - 'VG'
  - 'UVG'
  - 'DVG'
  - 'TVG'
  - 'QTV'
  - 'QNV'
  - 'SEV'
  - 'SPV'
  - 'OVG'
  - 'NVG'
  - 'TG'