connection:
  mysql:
    enabled: false
    address: "localhost:3306"
    username: "root"
    password: ""
    database: "test"
  sqlite:
    file: "storage.sql"

items:
  example:
    # Nome identificador do item
    name: 'Example'
    # De quantos em quantos segundos irá gerar coins
    interval: 5
    # Quantidade de coins que será gerada a cada intervalo
    coins: 10
    # Item no menu
    item:
      material: WATCH
      data: 0
      displayName: '&aExample'

bonus:
  # Permissão para aumentar o limite de stack por item
  stack:
    # Sem limite de stack
    # moneyfarm.stackinfinite
    stackinfinite: -1
    # moneyfarm.stack4
    stack4: 30
    # moneyfarm.stack3
    stack3: 25
    # moneyfarm.stack2
    stack2: 20
    # moneyfarm.stack1
    stack1: 15
    # Sem permissão
    default: 5

  # Permissão para multiplicar a quantidade de coins gerada
  generate:
    # moneyfarm.generate5
    generate5: 1.55
    # moneyfarm.generate4
    generate4: 1.45
    # moneyfarm.generate3
    generate3: 1.35
    # moneyfarm.generate2
    generate2: 1.25
    # moneyfarm.generate1
    generate1: 1.15

currency-format:
  - ''
  - 'k'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'OC'
  - 'N'
  - 'D'
  - 'UN'
  - 'DD'
  - 'TR'
  - 'QT'
  - 'QN'
  - 'SD'
  - 'SPD'
  - 'OD'
  - 'ND'
  - 'VG'
  - 'UVG'
  - 'DVG'
  - 'TVG'
  - 'QTV'
  - 'QNV'
  - 'SEV'
  - 'SPV'
  - 'OVG'
  - 'NVG'
  - 'TG'